import {
    studentDetailCourse,
    submittedCourse,
    schedule,
    courseStartPeriod,
    getChooseSubjectList,
} from './mock/courseStudentDetail.js';

export default {
    // 选课学生端
    'GET /api/choose/courseStartPeriod': courseStartPeriod, // 已选课程列表
    'GET /api/choose/subjectList': getChooseSubjectList, // 学科类型列表
    'POST /api/choose/listCourse': studentDetailCourse, // 可选课程列表
    'GET /api/choose/submittedCourse': submittedCourse, // 已选课程列表
    'POST /api/choose/schedule': schedule, // 小课表

    'GET /api/public/schdedule/templateForPc': {
        ifLogin: true,
        status: true,
        message: 'successful',
        code: 0,
        content: [
            [
                {
                    templateId: 13055,
                    name: '让我们荡起双桨',
                    eName: 'ceeasda',
                    startTime: 1545782400000,
                    endTime: 1545825600000,
                    playground: null,
                    playgroundId: 0,
                    outsidePlaygroundName: '阿萨德',
                    playgroundEname: null,
                    schoolName: null,
                    schoolEname: null,
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: [
                        {
                            id: 113,
                            orgId: null,
                            name: '测试2组',
                            eName: null,
                            ifIsNecessary: true,
                        },
                    ],
                    teachers: null,
                    students: null,
                    scheduleType: 3,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: true,
                    repeatCycle: null,
                    repeatIntervals: 1,
                    repeatType: 1,
                    repeatEndTime: 1545839999999,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: '测试测试测试',
                    allDay: true,
                },
            ],
            [
                {
                    templateId: 12260,
                    name: '语文😁',
                    eName: 'StringTest',
                    startTime: 1545696000000,
                    endTime: 1545697200000,
                    playground: '广交楼',
                    playgroundId: 2,
                    outsidePlaygroundName: null,
                    playgroundEname: '',
                    schoolName: '杭州校区',
                    schoolEname: 'HangZhou xiaoqu',
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: [
                        {
                            id: 27,
                            orgId: null,
                            name: '财务',
                            eName: null,
                            ifIsNecessary: true,
                        },
                    ],
                    teachers: [
                        {
                            userId: 3,
                            userName: '曾艳',
                            userEname: 'jessie',
                            avatarUrl: 'http://userservice.api.yungu-inc.org/api/user/avatarUrl/20',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                    ],
                    students: null,
                    scheduleType: 2,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: false,
                    repeatCycle: null,
                    repeatIntervals: null,
                    repeatType: null,
                    repeatEndTime: null,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: '表情测试',
                    allDay: false,
                },
                {
                    templateId: 12268,
                    name: '数学 G7',
                    eName: 'test',
                    startTime: 1545697800000,
                    endTime: 1545699600000,
                    playground: '体育馆舞蹈房',
                    playgroundId: 5,
                    outsidePlaygroundName: null,
                    playgroundEname: 'wenxi dancing room',
                    schoolName: '杭州云谷学校',
                    schoolEname: 'Hangzhou Yungu School',
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: [
                        {
                            id: 114,
                            orgId: null,
                            name: '测试A组',
                            eName: null,
                            ifIsNecessary: true,
                        },
                    ],
                    teachers: [
                        {
                            userId: 1447,
                            userName: '魏宇',
                            userEname: 'Weiyu',
                            avatarUrl:
                                'http://userservice.api.yungu-inc.org/api/user/avatarUrl/0150b9fb-e7a5-45b5-as87-b6dfea5dc27d',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                    ],
                    students: null,
                    scheduleType: 2,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: false,
                    repeatCycle: null,
                    repeatIntervals: null,
                    repeatType: null,
                    repeatEndTime: null,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: null,
                    allDay: false,
                },
                {
                    templateId: 12274,
                    name: '音乐 G6',
                    eName: 'New&OldTest',
                    startTime: 1545706800000,
                    endTime: 1545708000000,
                    playground: '广交楼',
                    playgroundId: 2,
                    outsidePlaygroundName: null,
                    playgroundEname: '',
                    schoolName: '杭州校区',
                    schoolEname: 'HangZhou xiaoqu',
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: [
                        {
                            id: 27,
                            orgId: null,
                            name: '财务',
                            eName: null,
                            ifIsNecessary: true,
                        },
                    ],
                    teachers: [
                        {
                            userId: 6,
                            userName: '韩央央',
                            userEname: 'Joyce Han',
                            avatarUrl:
                                'http://userservice.api.yungu-inc.org/api/user/avatarUrl/1357b92f-351b-47b5-b890-03e41e9b0f4c',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                    ],
                    students: null,
                    scheduleType: 2,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: false,
                    repeatCycle: null,
                    repeatIntervals: null,
                    repeatType: null,
                    repeatEndTime: null,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: '新旧版本测试',
                    allDay: false,
                },
                {
                    templateId: 12276,
                    name: '测试老的行事历',
                    eName: 'test',
                    startTime: 1545727200000,
                    endTime: 1545728400000,
                    playground: '文晖苑',
                    playgroundId: 1,
                    outsidePlaygroundName: null,
                    playgroundEname: '',
                    schoolName: '杭州校区',
                    schoolEname: 'HangZhou xiaoqu',
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: [
                        {
                            id: 31,
                            orgId: null,
                            name: '技术',
                            eName: null,
                            ifIsNecessary: true,
                        },
                    ],
                    teachers: [
                        {
                            userId: 181,
                            userName: '李会月',
                            userEname: 'lhy',
                            avatarUrl: 'http://userservice.api.yungu-inc.org/api/user/avatarUrl/78',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                        {
                            userId: 19,
                            userName: '陈杭',
                            userEname: 'Hang Chen',
                            avatarUrl:
                                'http://userservice.api.yungu-inc.org/api/user/avatarUrl/4a61435b-a737-4c04-a2ac-5bc627da84a7',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                    ],
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: false,
                    repeatCycle: null,
                    repeatIntervals: null,
                    repeatType: null,
                    repeatEndTime: null,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: '臭娃 ',
                    allDay: false,
                },
            ],
            [
                {
                    templateId: 12295,
                    name: '双版本日程测试',
                    eName: 'DoubleVersionTest',
                    startTime: 1545793200000,
                    endTime: 1545794400000,
                    playground: null,
                    playgroundId: 0,
                    outsidePlaygroundName: '广交楼',
                    playgroundEname: null,
                    schoolName: null,
                    schoolEname: null,
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: null,
                    teachers: null,
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: false,
                    repeatCycle: null,
                    repeatIntervals: null,
                    repeatType: null,
                    repeatEndTime: null,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: '测试',
                    allDay: false,
                },
                {
                    templateId: 12296,
                    name: '测试部门',
                    eName: 'test',
                    startTime: 1545782400000,
                    endTime: 1545786000000,
                    playground: '餐厅+种植地',
                    playgroundId: 7,
                    outsidePlaygroundName: null,
                    playgroundEname: 'Planting land',
                    schoolName: '杭州云谷学校',
                    schoolEname: 'Hangzhou Yungu School',
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: [
                        {
                            id: 114,
                            orgId: null,
                            name: '测试A组',
                            eName: null,
                            ifIsNecessary: true,
                        },
                    ],
                    teachers: null,
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: false,
                    repeatCycle: null,
                    repeatIntervals: null,
                    repeatType: null,
                    repeatEndTime: null,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: '测试测试测试备注',
                    allDay: false,
                },
                {
                    templateId: 12297,
                    name: '测试',
                    eName: 'test',
                    startTime: 1545782400000,
                    endTime: 1545786000000,
                    playground: '文晖苑',
                    playgroundId: 1,
                    outsidePlaygroundName: null,
                    playgroundEname: '',
                    schoolName: '杭州校区',
                    schoolEname: 'HangZhou xiaoqu',
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: [
                        {
                            id: 114,
                            orgId: null,
                            name: '测试A组',
                            eName: null,
                            ifIsNecessary: true,
                        },
                    ],
                    teachers: null,
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: false,
                    repeatCycle: null,
                    repeatIntervals: null,
                    repeatType: null,
                    repeatEndTime: null,
                    ifHavePower: false,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: null,
                    allDay: false,
                },
                {
                    templateId: 13055,
                    name: '测试全天日程',
                    eName: 'ceeasda',
                    startTime: 1545782400000,
                    endTime: 1545825600000,
                    playground: null,
                    playgroundId: 0,
                    outsidePlaygroundName: '阿萨德',
                    playgroundEname: null,
                    schoolName: null,
                    schoolEname: null,
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: [
                        {
                            id: 113,
                            orgId: null,
                            name: '测试2组',
                            eName: null,
                            ifIsNecessary: true,
                        },
                    ],
                    teachers: null,
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: true,
                    repeatCycle: null,
                    repeatIntervals: 1,
                    repeatType: 1,
                    repeatEndTime: 1545839999999,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: '测试测试测试',
                    allDay: true,
                },
                {
                    templateId: 13055,
                    name: '测试全天日程',
                    eName: 'ceeasda',
                    startTime: 1545782400000,
                    endTime: 1545825600000,
                    playground: null,
                    playgroundId: 0,
                    outsidePlaygroundName: '阿萨德',
                    playgroundEname: null,
                    schoolName: null,
                    schoolEname: null,
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: [
                        {
                            id: 113,
                            orgId: null,
                            name: '测试2组',
                            eName: null,
                            ifIsNecessary: true,
                        },
                    ],
                    teachers: null,
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: true,
                    repeatCycle: null,
                    repeatIntervals: 1,
                    repeatType: 1,
                    repeatEndTime: 1545839999999,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: '测试测试测试',
                    allDay: true,
                },
                {
                    templateId: 13060,
                    name: '1111测试链接',
                    eName: '就提升',
                    startTime: 1545782400000,
                    endTime: 1545786000000,
                    playground: '广交楼',
                    playgroundId: 2,
                    outsidePlaygroundName: null,
                    playgroundEname: '',
                    schoolName: '杭州校区',
                    schoolEname: 'HangZhou xiaoqu',
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: [
                        {
                            id: 31,
                            orgId: null,
                            name: '技术',
                            eName: null,
                            ifIsNecessary: true,
                        },
                    ],
                    teachers: [
                        {
                            userId: 1054,
                            userName: '陈寅仕',
                            userEname: 'test',
                            avatarUrl:
                                'http://userservice.api.yungu-inc.org/api/user/avatarUrl/69fc350d-b511-4832-b1bf-53e1b6bf952f',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                    ],
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: true,
                    repeatCycle: null,
                    repeatIntervals: 2,
                    repeatType: 1,
                    repeatEndTime: 1547135999000,
                    ifHavePower: false,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: '测试',
                    allDay: false,
                },
            ],
            [
                {
                    templateId: 13062,
                    name: '测试2周一次发消息222',
                    eName: '测试',
                    startTime: 1545885720000,
                    endTime: 1545894000000,
                    playground: '广交楼',
                    playgroundId: 2,
                    outsidePlaygroundName: null,
                    playgroundEname: '',
                    schoolName: '杭州校区',
                    schoolEname: 'HangZhou xiaoqu',
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: [
                        {
                            id: 31,
                            orgId: null,
                            name: '技术',
                            eName: null,
                            ifIsNecessary: true,
                        },
                    ],
                    teachers: [
                        {
                            userId: 1054,
                            userName: '陈寅仕',
                            userEname: 'test',
                            avatarUrl:
                                'http://userservice.api.yungu-inc.org/api/user/avatarUrl/69fc350d-b511-4832-b1bf-53e1b6bf952f',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                    ],
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: true,
                    repeatCycle: 4,
                    repeatIntervals: 2,
                    repeatType: 2,
                    repeatEndTime: 1558713599000,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: '测',
                    allDay: false,
                },
                {
                    templateId: 13063,
                    name: '再次日常测试30分钟',
                    eName: '日常test前三十分钟',
                    startTime: 1545899280000,
                    endTime: 1545901200000,
                    playground: '文晖苑',
                    playgroundId: 1,
                    outsidePlaygroundName: null,
                    playgroundEname: '',
                    schoolName: '杭州校区',
                    schoolEname: 'HangZhou xiaoqu',
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: null,
                    teachers: [
                        {
                            userId: 1447,
                            userName: '魏宇',
                            userEname: 'Weiyu',
                            avatarUrl:
                                'http://userservice.api.yungu-inc.org/api/user/avatarUrl/0150b9fb-e7a5-45b5-as87-b6dfea5dc27d',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                        {
                            userId: 181,
                            userName: '李会月',
                            userEname: 'lhy',
                            avatarUrl: 'http://userservice.api.yungu-inc.org/api/user/avatarUrl/78',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                    ],
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: false,
                    repeatCycle: null,
                    repeatIntervals: null,
                    repeatType: null,
                    repeatEndTime: null,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: 'cei ',
                    allDay: false,
                },
                {
                    templateId: 13066,
                    name: '测试半小时之后发送的',
                    eName: '测试test半小时之后发送的',
                    startTime: 1545898200000,
                    endTime: 1545901200000,
                    playground: '广交楼',
                    playgroundId: 2,
                    outsidePlaygroundName: null,
                    playgroundEname: '',
                    schoolName: '杭州校区',
                    schoolEname: 'HangZhou xiaoqu',
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: null,
                    teachers: [
                        {
                            userId: 1447,
                            userName: '魏宇',
                            userEname: 'Weiyu',
                            avatarUrl:
                                'http://userservice.api.yungu-inc.org/api/user/avatarUrl/0150b9fb-e7a5-45b5-as87-b6dfea5dc27d',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                        {
                            userId: 181,
                            userName: '李会月',
                            userEname: 'lhy',
                            avatarUrl: 'http://userservice.api.yungu-inc.org/api/user/avatarUrl/78',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                    ],
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: false,
                    repeatCycle: null,
                    repeatIntervals: null,
                    repeatType: null,
                    repeatEndTime: null,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: '地方撒',
                    allDay: false,
                },
                {
                    templateId: 13067,
                    name: '修改测试2',
                    eName: 'UpdateTestTwo',
                    startTime: 1545897600000,
                    endTime: 1545898800000,
                    playground: '广交楼',
                    playgroundId: 2,
                    outsidePlaygroundName: null,
                    playgroundEname: '',
                    schoolName: '杭州校区',
                    schoolEname: 'HangZhou xiaoqu',
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: null,
                    teachers: [
                        {
                            userId: 3,
                            userName: '曾艳',
                            userEname: 'jessie',
                            avatarUrl: 'http://userservice.api.yungu-inc.org/api/user/avatarUrl/20',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                    ],
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: true,
                    repeatCycle: null,
                    repeatIntervals: 1,
                    repeatType: 1,
                    repeatEndTime: 1545926399000,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: null,
                    allDay: false,
                },
            ],
            [
                {
                    templateId: 13059,
                    name: '测试全天日程',
                    eName: 'ceeasda',
                    startTime: 1545955200000,
                    endTime: 1545998400000,
                    playground: null,
                    playgroundId: 0,
                    outsidePlaygroundName: '阿萨德',
                    playgroundEname: null,
                    schoolName: null,
                    schoolEname: null,
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: [
                        {
                            id: 113,
                            orgId: null,
                            name: '测试2组',
                            eName: null,
                            ifIsNecessary: true,
                        },
                    ],
                    teachers: null,
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: true,
                    repeatCycle: null,
                    repeatIntervals: 1,
                    repeatType: 1,
                    repeatEndTime: 1546012799999,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: '测试测试测试',
                    allDay: true,
                },
                {
                    templateId: 13060,
                    name: '1111测试链接',
                    eName: '就提升',
                    startTime: 1545955200000,
                    endTime: 1545958800000,
                    playground: '广交楼',
                    playgroundId: 2,
                    outsidePlaygroundName: null,
                    playgroundEname: '',
                    schoolName: '杭州校区',
                    schoolEname: 'HangZhou xiaoqu',
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: [
                        {
                            id: 31,
                            orgId: null,
                            name: '技术',
                            eName: null,
                            ifIsNecessary: true,
                        },
                    ],
                    teachers: [
                        {
                            userId: 1054,
                            userName: '陈寅仕',
                            userEname: 'test',
                            avatarUrl:
                                'http://userservice.api.yungu-inc.org/api/user/avatarUrl/69fc350d-b511-4832-b1bf-53e1b6bf952f',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                    ],
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: true,
                    repeatCycle: null,
                    repeatIntervals: 2,
                    repeatType: 1,
                    repeatEndTime: 1547135999000,
                    ifHavePower: false,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: '测试',
                    allDay: false,
                },
                {
                    templateId: 13069,
                    name: '修改测试2111gdbdfbd',
                    eName: 'UpdateTestTwofs',
                    startTime: 1545984000000,
                    endTime: 1545985200000,
                    playground: '广交楼',
                    playgroundId: 2,
                    outsidePlaygroundName: null,
                    playgroundEname: '',
                    schoolName: '杭州校区',
                    schoolEname: 'HangZhou xiaoqu',
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: null,
                    teachers: [
                        {
                            userId: 3,
                            userName: '曾艳',
                            userEname: 'jessie',
                            avatarUrl: 'http://userservice.api.yungu-inc.org/api/user/avatarUrl/20',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                        {
                            userId: 181,
                            userName: '李会月',
                            userEname: 'lhy',
                            avatarUrl: 'http://userservice.api.yungu-inc.org/api/user/avatarUrl/78',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                    ],
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: true,
                    repeatCycle: null,
                    repeatIntervals: 1,
                    repeatType: 1,
                    repeatEndTime: 1546185599000,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: null,
                    allDay: false,
                },
            ],
            [
                {
                    templateId: 13069,
                    name: '修改测试2111gdbdfbd',
                    eName: 'UpdateTestTwofs',
                    startTime: 1546070400000,
                    endTime: 1546071600000,
                    playground: '广交楼',
                    playgroundId: 2,
                    outsidePlaygroundName: null,
                    playgroundEname: '',
                    schoolName: '杭州校区',
                    schoolEname: 'HangZhou xiaoqu',
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: null,
                    teachers: [
                        {
                            userId: 3,
                            userName: '曾艳',
                            userEname: 'jessie',
                            avatarUrl: 'http://userservice.api.yungu-inc.org/api/user/avatarUrl/20',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                        {
                            userId: 181,
                            userName: '李会月',
                            userEname: 'lhy',
                            avatarUrl: 'http://userservice.api.yungu-inc.org/api/user/avatarUrl/78',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                    ],
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: true,
                    repeatCycle: null,
                    repeatIntervals: 1,
                    repeatType: 1,
                    repeatEndTime: 1546185599000,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: null,
                    allDay: false,
                },
                {
                    templateId: 13081,
                    name: '测试全天日程222',
                    eName: 'ceeasda',
                    startTime: 1546041600000,
                    endTime: 1546084800000,
                    playground: null,
                    playgroundId: null,
                    outsidePlaygroundName: '阿萨德',
                    playgroundEname: null,
                    schoolName: null,
                    schoolEname: null,
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: [
                        {
                            id: 113,
                            orgId: null,
                            name: '测试2组',
                            eName: null,
                            ifIsNecessary: true,
                        },
                        {
                            id: 31,
                            orgId: null,
                            name: '技术',
                            eName: null,
                            ifIsNecessary: false,
                        },
                    ],
                    teachers: null,
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: false,
                    repeatCycle: null,
                    repeatIntervals: null,
                    repeatType: null,
                    repeatEndTime: null,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: '测试测试测试',
                    allDay: true,
                },
            ],
            [
                {
                    templateId: 13060,
                    name: '1111测试链接',
                    eName: '就提升',
                    startTime: 1546128000000,
                    endTime: 1546131600000,
                    playground: '广交楼',
                    playgroundId: 2,
                    outsidePlaygroundName: null,
                    playgroundEname: '',
                    schoolName: '杭州校区',
                    schoolEname: 'HangZhou xiaoqu',
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: [
                        {
                            id: 31,
                            orgId: null,
                            name: '技术',
                            eName: null,
                            ifIsNecessary: true,
                        },
                    ],
                    teachers: [
                        {
                            userId: 1054,
                            userName: '陈寅仕',
                            userEname: 'test',
                            avatarUrl:
                                'http://userservice.api.yungu-inc.org/api/user/avatarUrl/69fc350d-b511-4832-b1bf-53e1b6bf952f',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                    ],
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: true,
                    repeatCycle: null,
                    repeatIntervals: 2,
                    repeatType: 1,
                    repeatEndTime: 1547135999000,
                    ifHavePower: false,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: '测试',
                    allDay: false,
                },
                {
                    templateId: 13069,
                    name: '修改测试2111gdbdfbd',
                    eName: 'UpdateTestTwofs',
                    startTime: 1546156800000,
                    endTime: 1546158000000,
                    playground: '广交楼',
                    playgroundId: 2,
                    outsidePlaygroundName: null,
                    playgroundEname: '',
                    schoolName: '杭州校区',
                    schoolEname: 'HangZhou xiaoqu',
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: null,
                    teachers: [
                        {
                            userId: 3,
                            userName: '曾艳',
                            userEname: 'jessie',
                            avatarUrl: 'http://userservice.api.yungu-inc.org/api/user/avatarUrl/20',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                        {
                            userId: 181,
                            userName: '李会月',
                            userEname: 'lhy',
                            avatarUrl: 'http://userservice.api.yungu-inc.org/api/user/avatarUrl/78',
                            gradeName: null,
                            gradeEnglishName: null,
                            ifIsNecessary: true,
                            employeeId: null,
                        },
                    ],
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: true,
                    repeatCycle: null,
                    repeatIntervals: 1,
                    repeatType: 1,
                    repeatEndTime: 1546185599000,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: null,
                    allDay: false,
                },
                {
                    templateId: 13082,
                    name: '测试全天日程',
                    eName: 'ceeasda',
                    startTime: 1546128000000,
                    endTime: 1546171200000,
                    playground: null,
                    playgroundId: 0,
                    outsidePlaygroundName: '阿萨德',
                    playgroundEname: null,
                    schoolName: null,
                    schoolEname: null,
                    courseId: null,
                    courseName: null,
                    courseEnglishName: null,
                    departments: [
                        {
                            id: 113,
                            orgId: null,
                            name: '测试2组',
                            eName: null,
                            ifIsNecessary: true,
                        },
                    ],
                    teachers: null,
                    students: null,
                    scheduleType: 4,
                    timeType: null,
                    studentGroups: null,
                    joinNumbers: null,
                    calendarId: 1,
                    ifRepeat: true,
                    repeatCycle: null,
                    repeatIntervals: 1,
                    repeatType: 1,
                    repeatEndTime: 1546271999000,
                    ifHavePower: true,
                    departmentNecessaryModel: null,
                    userNecessaryModel: null,
                    remark: '测试测试测试',
                    allDay: true,
                },
            ],
        ],
        ifAdmin: false,
    },
};
