import {
    teacherOrgData,
    departmentalStaff,
    orgInfoById,
    createOrgSuccess,
    deleteOrgSuccess,
    addTeacherList,
    getPathByTreeId,
    addStaffSuccess,
    deleteStaffSuccess,
    fetchOrgDetailSuccess,
    updateOrgTreeNode,
    setOrgRoleSuccess,
    getOrgRoleList,
    getConfigureRoleList,
    deleteUserForRoleSuccess,
    deleteOrgNodeRoleSuccess,
    adminGrade,
    transferStaffSuccess,
    addExternalUser,
    batchSetControllerSuccess,
    lookStaffDetail,
    dingNodeInfo,
    getEmployeeList,
    checkAddExternalEmployee,
    updateExternalEmployee,
    employeeQuitSuccess,
} from './mock/teacher.js';

export default {
    //员工管理
    'GET /api/teaching/listOrgTree': teacherOrgData,
    'POST /api/teaching/listUser': departmentalStaff,
    'GET /api/teaching/getOrgDetail': orgInfoById,
    'GET /api/teaching/getOrgCompletePath': getPathByTreeId,
    'POST /api/teaching/addOrgTreeNode': createOrgSuccess,
    'GET /api/teaching/deleteOrgTreeNode': deleteOrgSuccess,
    'GET /api/teaching/getUsers': addTeacherList,
    'POST /api/teaching/addUserToNode': addStaffSuccess,
    'POST /api/teaching/deletedUserFromNode': deleteStaffSuccess,
    'GET /api/teaching/select/org': fetchOrgDetailSuccess,
    'POST /api/teaching/updateOrgTreeNode': updateOrgTreeNode,
    'POST /api/teaching/setOrgNodeRole': setOrgRoleSuccess,
    'GET /api/getOrgRoleList': getOrgRoleList,
    'GET /api/teaching/listTreeNodeUseTag': getConfigureRoleList,
    'GET /api/teaching/deleteUserForRole': deleteUserForRoleSuccess,
    'GET /api/teaching/deleteOrgNodeRole': deleteOrgNodeRoleSuccess,
    'GET /api/teaching/select/admin/grade': adminGrade,
    'POST /api/teaching/transferUser': transferStaffSuccess,
    'POST /api/teaching/addExternalEmployee': addExternalUser,
    'POST /api/teaching/checkAddExternalEmployee': checkAddExternalEmployee,
    'POST /api/teaching/batchUpdateLeader': batchSetControllerSuccess,
    'GET /api/teaching/userDetail': lookStaffDetail,
    'GET /test/test': dingNodeInfo,
    'POST /api/teaching/updateExternalEmployee': updateExternalEmployee,

    //外聘员工离职
    'GET /api/teaching/quitExternalEmployee': employeeQuitSuccess,
    //获取直线主管列表 、在职员工列表
    'GET /api/teaching/getEmployee': getEmployeeList,
};
